# -*- coding: utf-8 -*-
"""ajpes_workerji.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gOnMlLe5pJGjgiCQqlOKindkuWqbUPTh
"""

import asyncio
import csv
import os
from pathlib import Path
from typing import Dict, List, Optional, Set

import pandas as pd
from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeoutError
import nest_asyncio

VHODNA_DATOTEKA = "opsiprs.csv"
IZHODNA_DATOTEKA = "ajpes_osebe.csv"
AJPES_URL = "https://www.ajpes.si/"

MAX_WORKERS = 5
QUEUE_SIZE = 500
SAVE_EVERY = 50
HEADLESS = True

LIMIT_ROWS: Optional[int] = None

FIELDNAMES = [
    "Matična številka podjetja",
    "Telefon",
    "Email",
    "Datum vpisa",
    "Status aktivnosti",
    "Velikost",
    "Glavna dejavnost",
    "Druge dejavnosti",
    "Zastopniki",
    "Ustanovitelji",
    "Lastniki",
    "Prokurist",
    "Družbeniki",
    "Direktor",
    "Uprava",
    "Člani nadzornega sveta",
    "Nosilec dejavnosti",
    "Partnerji",
]


def read_input_csv(path: str) -> pd.DataFrame:
    """Robustno prebere CSV, tudi če je UTF-16/Windows encoding."""
    encodings = ["utf-8-sig", "utf-16", "utf-16-le", "cp1250", "latin1"]

    last_error = None
    for enc in encodings:
        try:
            df = pd.read_csv(
                path,
                encoding=enc,
                sep=None,
                engine="python",
                on_bad_lines="skip",
            )
            print(f"[+] CSV prebran z encoding={enc}, vrstic={len(df)}")
            return df
        except Exception as e:
            last_error = e

    raise RuntimeError(f"CSV ni bilo mogoče prebrati. Zadnja napaka: {last_error}")


def load_done_maticne(output_path: str) -> Set[str]:
    """Prebere že obdelane matične številke iz output datoteke, da lahko nadaljuješ po crashu."""
    if not os.path.exists(output_path) or os.path.getsize(output_path) == 0:
        return set()

    try:
        done_df = pd.read_csv(output_path, encoding="utf-8-sig", dtype=str)
        if "Matična številka podjetja" not in done_df.columns:
            return set()
        done = set(done_df["Matična številka podjetja"].dropna().astype(str).str.strip())
        print(f"[+] Najdenih že obdelanih: {len(done)}")
        return done
    except Exception as e:
        print(f"[!] Ne morem prebrati obstoječega outputa, nadaljujem brez skipanja: {e}")
        return set()


def normalize_maticna(value) -> str:
    if pd.isna(value):
        return ""
    s = str(value).strip()
    if s.endswith(".0"):
        s = s[:-2]
    return s


async def speed_up_page(page):
    """Blokira nepotrebne vire. Ne blokiramo CSS/JS, ker stran lahko uporablja layout in skripte."""
    async def route_handler(route):
        resource_type = route.request.resource_type
        if resource_type in {"image", "font", "media"}:
            await route.abort()
        else:
            await route.continue_()

    await page.route("**/*", route_handler)
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(20000)


async def handle_login(page) -> bool:
    """Anonimna prijava. Če je uporabnik že prijavljen, samo vrne True."""
    try:
        osnovni_podatki = page.locator("h4:has-text('OSNOVNI PODATKI')")
        if await osnovni_podatki.count() > 0:
            return True

        login_btn = page.locator("a.btn.btn-warning:has-text('PRIJAVA V SISTEM')")
        if await login_btn.count() == 0:
            return await osnovni_podatki.count() > 0

        print("   [!] LOGIN potreben")
        await login_btn.first.click()

        anon = page.locator("text=Vstopi kot anonimni uporabnik")
        await anon.wait_for(state="visible", timeout=10000)
        await anon.click()

        nadaljuj = page.locator("button.btn.btn-success:has-text('Nadaljuj s prijavo')")
        await nadaljuj.wait_for(state="visible", timeout=10000)
        await nadaljuj.click()

        await page.locator("h4:has-text('OSNOVNI PODATKI')").wait_for(timeout=15000)
        return True

    except Exception as e:
        print(f"   [!] LOGIN ERROR: {e}")
        return False


async def search_company(page, maticna: str) -> bool:
    try:
        await page.goto(AJPES_URL, wait_until="domcontentloaded")

        search_input = page.locator("#prva_OsnovnoIskanje")
        await search_input.wait_for(state="visible", timeout=10000)
        await search_input.fill(maticna)

        await page.locator("input[type='submit'][value='IŠČI']").first.click()

        try:
            await page.wait_for_load_state("domcontentloaded", timeout=15000)
        except PlaywrightTimeoutError:
            pass

        ok = await handle_login(page)
        if not ok:
            return False

        await page.locator("h4:has-text('OSNOVNI PODATKI')").wait_for(timeout=10000)
        return True

    except Exception as e:
        print(f"   [!] Napaka pri iskanju {maticna}: {e}")
        return False


async def scrape_osebe(page, maticna: str) -> Dict[str, str]:
    company_data = {field: "" for field in FIELDNAMES}
    company_data["Matična številka podjetja"] = maticna

    rows = page.locator("div.row")
    count = await rows.count()

    for i in range(count):
        row = rows.nth(i)
        try:
            label_el = row.locator("div.col-sm-5.text-thin")
            if await label_el.count() == 0:
                continue

            value_el = row.locator("div.col-sm-7")
            if await value_el.count() == 0:
                continue

            label = (await label_el.first.inner_text()).strip()
            text = (await value_el.first.inner_text()).strip()

            if not label or not text:
                continue

            cleaned = " | ".join(t.strip() for t in text.split("\n") if t.strip())

            if label == "Telefon":
                target = "Telefon"
            elif label == "Elektronski naslov":
                target = "Email"
            else:
                target = label

            if target in company_data:
                if company_data[target]:
                    company_data[target] += " | " + cleaned
                else:
                    company_data[target] = cleaned

        except Exception:
            continue

    return company_data


async def worker(worker_id: int, browser, job_queue: asyncio.Queue, result_queue: asyncio.Queue):
    context = await browser.new_context()
    page = await context.new_page()
    await speed_up_page(page)

    while True:
        item = await job_queue.get()
        if item is None:
            job_queue.task_done()
            break

        idx, total, maticna = item
        print(f"\n[W{worker_id}] --- ({idx}/{total}) {maticna} ---")

        try:
            found = await search_company(page, maticna)
            if found:
                data = await scrape_osebe(page, maticna)
                await result_queue.put(data)
            else:
                empty = {field: "" for field in FIELDNAMES}
                empty["Matična številka podjetja"] = maticna
                await result_queue.put(empty)
                print(f"[W{worker_id}] [!] Podjetje ni bilo najdeno ali login ni uspel")

        except Exception as e:
            print(f"[W{worker_id}] [!] ERROR {maticna}: {e}")

        finally:
            job_queue.task_done()

    await page.close()
    await context.close()


async def writer(result_queue: asyncio.Queue, output_path: str):
    file_exists = os.path.exists(output_path) and os.path.getsize(output_path) > 0
    written = 0

    with open(output_path, "a", newline="", encoding="utf-8-sig") as f:
        writer_obj = csv.DictWriter(
            f,
            fieldnames=FIELDNAMES,
            extrasaction="ignore",
        )

        if not file_exists:
            writer_obj.writeheader()
            f.flush()

        while True:
            item = await result_queue.get()
            if item is None:
                result_queue.task_done()
                break

            writer_obj.writerow(item)
            written += 1

            if written % SAVE_EVERY == 0:
                f.flush()
                os.fsync(f.fileno())
                print(f"[SAVE] Zapisanih novih vrstic: {written}")

            result_queue.task_done()

        f.flush()
        os.fsync(f.fileno())


async def main():
    df = read_input_csv(VHODNA_DATOTEKA)

    if "Matična številka" not in df.columns:
        raise RuntimeError(f"Manjka stolpec 'Matična številka'. Stolpci v CSV: {list(df.columns)}")

    if LIMIT_ROWS is not None:
        df = df.head(LIMIT_ROWS)

    done = load_done_maticne(IZHODNA_DATOTEKA)

    maticne: List[str] = []
    for value in df["Matična številka"]:
        m = normalize_maticna(value)
        if m and m not in done:
            maticne.append(m)

    total = len(maticne)
    print(f"[+] Za obdelavo po skipanju: {total}")
    print(f"[+] Workers: {MAX_WORKERS}")

    if total == 0:
        print("[+] Ni nič za obdelati.")
        return

    job_queue = asyncio.Queue(maxsize=QUEUE_SIZE)
    result_queue = asyncio.Queue(maxsize=QUEUE_SIZE)

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=HEADLESS)

        writer_task = asyncio.create_task(writer(result_queue, IZHODNA_DATOTEKA))

        worker_tasks = [
            asyncio.create_task(worker(i + 1, browser, job_queue, result_queue))
            for i in range(MAX_WORKERS)
        ]

        for idx, maticna in enumerate(maticne, start=1):
            await job_queue.put((idx, total, maticna))

        for _ in range(MAX_WORKERS):
            await job_queue.put(None)

        await job_queue.join()
        await asyncio.gather(*worker_tasks)

        await result_queue.put(None)
        await result_queue.join()
        await writer_task

        await browser.close()

    print("\nKONČANO")
    print(f"Output: {Path(IZHODNA_DATOTEKA).resolve()}")


if __name__ == "__main__":
    nest_asyncio.apply()
    asyncio.run(main())