name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'FE/**'        

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd FE
          npm install
      
      - name: Build
        run: |
          cd FE
          npm run build
